temp_unit: celsius
url: "https://api.open-meteo.com/v1/forecast"
params:
  latitude: 52.52
  longitude: 13.41
  hourly: 
    - "temperature_2m"
    - "precipitation"
    - "wind_speed_10m"
  current:
    - "temperature_2m"
    - "relative_humidity_2m"
